### ISSUE TITLE
Issue with too many shows

### ISSUE THREAD

**Issue by dragoneat666** [Opaque02/Plex-EpisodeNotifier#3] opened 2021-08-18 18:55 UTC
Hi, I really enjoy what this can do. The only problem I am running into is that it is trying to print all my shows in Plex, which is what its supposed to do, obviously.
Problem is that I have over 250 shows. I was able to change the small amount of code so that it does not pin the messages, as discords has a 50 pin limit. It will then just put all the shows in, which works fine until it reaches the end, then Discord just removes some of the messages. Currently the list will show me B - O, but #, A, P - Z are not showing anymore.
I was wondering if there was a way to implement so it will only track shows that are still airing, instead of every show?

**Comment by Opaque02** [comment] 2021-08-19 12:18
Ah, I know what the issue is. Unfortunately I didn't account for hitting Discord's pin limit (I didn't even know there was one!)

So the way the bot works is by breaking it down into 3 sections. First, it'll delete any messages in the channel that aren't pinned. This is to remove all the $ commands that are put into the channel, leaving it nice and clean. Secondly, it then prints all the shows you have and pins them, and then finally deletes all the unpinned messages again (since now you have a bunch of messages that say "Message pinned to channel" etc, which doesn't look great between each show)

Because of that last step, if you make it unpin the messages, it'll also try to delete the messages that aren't pinned. There may be a max limit on how much can be deleted at once, but again I didn't check since I wasn't expecting it to get that big.

In theory if you don't mind the $ commands being there, you could get rid of the pinning AND deleting sections, but it'll have all the $ commands you use. Alternatively, you could make it so that when you do a $ command, the first thing it does is to delete the last message before doing anything else. I thought about making it do that, but was worried about other commands intersecting (since if another user uses a $ command just before you and something starts printing, you may delete what the bot was trying to actually print if that makes sense?)

The last option would be to have it search the previous X messages (you could make a variable to choose how many messages it searches through), and if it finds a $ command, to delete only that message - that way it'll delete the right messages, not rely on having to pin everything, and also not rely on going past the limit on deleting old messages too. In theory that *should* work, and should be the best option, but would also be more effort.

It comes down to how many people are using the discord server at once - if it's not many, you could go with option 2, which isn't too hard, but less reliable. If you have a lot and want it to be perfect, option 3 is probably the best. If you just want the easiest thing and don't mind it being a little messy, option 1 is the way to go. There may even be other options out there that would do the job, but none that come to mind!

**Comment by dragoneat666** [comment] 2021-08-19 13:50
I did not see that it was deleting messages, I managed to not realize what Purge meant lol!
That worked perfectly though, having the $ commands are not a big deal actually, i also dont mind having to delete those manually if I needed to anyway. The other idea I could add: I dont automate my server as much as others, I like manually managing it. So I am the only person who updates, so whenever I do update it, I will just run the $update command. 

Thank you for everything with this!

**Comment by Opaque02** [comment] 2021-08-19 13:53
Yeah, it took me a while to find the purge command because I was looking for delete or clear or something :-P!

Glad it all worked out, and that it was easy enough to do! I'm going to close the issue - Ihooe with that you get a lot of usage out of it, and that you enjoy the notifier :-)! 

Enjoy!

**Closed as completed by Opaque02** 2021-08-19 13:53 UTC
